### ISSUE TITLE
Close the modal

### ISSUE THREAD

**Issue by fonfon6666** [marksmccann/modality#3]
Hello,

I click on "Profil" to open the first modal, and i don't find the solution for closing the opened modal when i click on other button (Médias, Portée du projet, Entreprises).

I hope that my question is understandable :-)

Have you a solution ?

**Comment by marksmccann** [comment]
Essentially, you only want one modal open at a time? 

Modality wasn't designed to do this, but you can add that ability pretty easily. Here is one way to do it; replace your JS with this:

``` javascript
Modality.init( '#profil, #medias, #portee, #entreprises, #financement, #don', { 
    effect: 'fade',
    onOpen: function() {
        var M = Modality, m = M.instances; 
        if( !M.open ) M.open = ''; // create 'open' attribute to store open modal
        if( M.open != '' ) { M.open.close(); M.open = ''; } // close modal and reset attribute
        for( var i in m ) { if( m[i].isOpen() ) M.open = m[i]; } // find & save open modal
    } 
});
```

**Comment by fonfon6666** [comment]
Perfect !!!!!!!!!!!!

Thank you very much !!!
